# Generated by hand to alter Blog.image upload_to and migrate existing files
from django.db import migrations, models

def move_files_and_strip_prefix(apps, schema_editor):
    import os
    import shutil
    from django.conf import settings

    Blog = apps.get_model('blogapp', 'Blog')
    media_root = getattr(settings, 'MEDIA_ROOT', '')
    if not media_root:
        return

    for blog in Blog.objects.exclude(image='').exclude(image=None):
        name = blog.image.name
        if name.startswith('blog_images/'):
            filename = name.split('/', 1)[1]
            src = os.path.join(media_root, name.replace('/', os.sep))
            dst = os.path.join(media_root, filename)
            # Create destination directory if needed (root expected)
            try:
                if os.path.exists(src):
                    if not os.path.exists(dst):
                        # Ensure parent exists
                        os.makedirs(os.path.dirname(dst), exist_ok=True)
                        shutil.move(src, dst)
                    # Update DB path to filename only
                    blog.image.name = filename
                    blog.save(update_fields=['image'])
                else:
                    # If source missing, still strip prefix in DB
                    blog.image.name = filename
                    blog.save(update_fields=['image'])
            except Exception:
                # Best-effort migration; skip on error
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RunPython(move_files_and_strip_prefix, migrations.RunPython.noop),
    ]



